I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/endings/battle.rpy", line 65, in script
    "APERTURE SCIENCE CORE CONTROL CENTER (ASC3)\n[[ YIELD ] COMMAND\n\nYIELD ATTEMPTS A HACK INTO MAIN CORE SYSTEMS. 50% CHANCE OF STUNNING CORE FOR ONE (1) CYCLE. CHANCE DECREASES WITH EACH USE."
ValueError: unsupported format character 'C' (0x43) at index 114

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/endings/battle.rpy", line 65, in script
    "APERTURE SCIENCE CORE CONTROL CENTER (ASC3)\n[[ YIELD ] COMMAND\n\nYIELD ATTEMPTS A HACK INTO MAIN CORE SYSTEMS. 50% CHANCE OF STUNNING CORE FOR ONE (1) CYCLE. CHANCE DECREASES WITH EACH USE."
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\exports\sayexports.py", line 121, in say
    what = what % tag_quoting_dict
ValueError: unsupported format character 'C' (0x43) at index 114

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.6.25022803
Aperture Dating Simulator 0.2.5alpha
Wed Jun 11 10:54:47 2025
