I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/endings/kristrue.rpy", line 14, in script
    scene nyc eve with fade
Exception: Image 'nyc' does not accept attributes 'eve'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/endings/kristrue.rpy", line 14, in script
    scene nyc eve with fade
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 1258, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 1087, in show_imspec
    renpy.config.show(name,
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Users\seven\Downloads\renpy-8.3.6-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'nyc' does not accept attributes 'eve'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.6.25022803
Aperture Dating Simulator 0.6.0alpha
Mon Jul  7 01:36:28 2025
